name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/919318155035/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '919318155035-compute@developer.gserviceaccount.com'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: regularizacionya-git
          region: europe-west1
          project_id: chatregularizacionya
          source: .

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
